# Calculates required commits for today based on image.text in repo and commits specified times
name: GenDocs

# Controls when the workflow will run
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: write
  
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install tvarsify
      run: pip install .
    - name: Generate Docs
      run: python gen_docs.py
      working-directory: tools

    - name: Commit Docs
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "Automated"
        if [ -n "$(git status --porcelain)" ]; then
          git add -v readme.md
          git commit -m '[AUTOMATED] readme.md' -- readme.md
        fi 

        if ! git diff --quiet HEAD origin/master -- readme.md; then
          git push
        fi
